language: ruby
rvm:
- 2.7.0
install: bundle install
services:
  - postgresql
env:
  - DB=pgsql
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rspec
